---
- name: Implement loops on multiple arguments
  hosts: all
  tasks:
    - name: Loops with multiple arguments
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: tree,b: absent,c: no}
        - {a: git,b: absent,c: no}
        - {a: maven,b: absent,c: no}
...
