---
- name: Create users and files
  hosts: all
  tasks:
    - name: Create users
      user:
        name: "{{a}}"
        password: "{{b}}"
        uid: "{{c}}"
    - name: File creation/directory creation
      file:
        name: "{{d}}"
        state: "{{e}}"
...
