---
- name: Install tomcat using play scope variables
  hosts: all
  vars:
    - a: tomcat9
    - b: present
    - c: yes
  tasks:
    - name: Install tomcat
      apt:
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
... 
