---
- name: Install sw using loops
  hosts: all
  serial: 1
  tasks:
    - name: Install three sw's using loops
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - tree
        - git
        - maven
...
