---
- name: Copy tomcat-users.xml and change port to 7070
  copy:
    src: "{{file1}}"
    dest: "{{dest1}}"
- name: Change the port number to 7070
  replace:
    regexp: "{{port1}}"
    replace: "{{port2}}"
    path: "{{path1}}"
  notify: Check url response
...
