---
# handlers file for tomcat9
- name: Check url response
  uri:
    url: "{{item.a}}"
    status_code: "{{item.b}}"
  with_items: 
    - {a: "{{server1}}",b: "{{status1}}"}
    - {a: "{{server2}}",b: "{{status1}}"}
...
