---
- name: Check URL response
  uri:
    url: "{{item.a}}"
    status_code: "{{item.b}}"
  with_items:
    - {a: "{{server1}}",b: "{{status}}"}
    - {a: "{{server2}}",b: "{{status}}"}
    - {a: "{{server3}}",b: "{{status}}"}
...
