---
- name: Copy tomcat-users.xml
  copy:
    src: "{{src1}}"
    dest: "{{dest1}}"
- name: Change port from 8080 to 9090
  replace:
    regexp: "{{port1}}"
    replace: "{{port2}}"
    path: "{{path1}}"
  notify: Restart tomcat9
...
